name: Xin Wang's Website
description: My page
permalink: /:categories/:year/:month/:title/
url: http://wangx23.github.io
markdown: kramdown
highlighter: rouge

navigation:
  - url: "/Research/"
    title: Research
  - url: "/Teaching/"
    title: Teaching
  - title: Github
    url: "http://github.com/wangx23"
