name: Xin Wang's Website
description: My page
permalink: /:categories/:year/:month/:title/
url: http://wangxin23.github.io
markdown: kramdown
highlighter: rouge

navigation:
  - url: "/Research/"
    title: Research
  - url: "/blog/"
    title: Blog
  - url: "/Chinese/"
    title: 我
  - title: Github
    url: "http://github.com/purplewish"
